services:
  inpsyght:
    container_name: inpsyght
    build:
      context: ./inpsyght-backend
      dockerfile: Dockerfile
    image: inpsyght:latest
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      STRAPI_LOG_LEVEL: debug
    volumes:
      # Volumes de código para hot-reloading (CORRETO)
      - ./inpsyght-backend/config:/opt/app/config
      - ./inpsyght-backend/src:/opt/app/src
      # Volume para o .env (CORRETO)
      - .env:/opt/app/.env
      # Volume para uploads persistentes (CORRETO)
      - ./inpsyght-backend/public/uploads:/opt/app/public/uploads

      # LINHAS PROBLEMÁTICAS REMOVIDAS:
      # - ./inpsyght-backend/package.json:/opt/inpsyght-backend/package.json (ERRADO E DESNECESSÁRIO)
      # - ./inpsyght-backend/package-lock.json:/opt/inpsyght-backend/package-lock.json (ERRADO E DESNECESSÁRIO)
      # - ./inpsyght-backend/config/certs/supabase-ca.crt:/opt/app/certs/supabase-ca.crt (DESNECESSÁRIO)
    ports:
      - '1337:1337'
    networks:
      - inpsyght
      
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      shm_size: 1gb
    image: frontend:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: 3000
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - inpsyght
    networks:
      - inpsyght
      
networks:
  inpsyght:
    name: Inpsyght
    driver: bridge