name: Sync Fork

on:
  schedule:
    - cron: '0 3 * * *' # todo dia às 03h UTC
  workflow_dispatch:    # permite rodar manualmente

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream
        run: git remote add upstream https://github.com/fclorenzo/inpsyght.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream/main
        run: |
          git checkout main
          git merge -X theirs upstream/main || true

      - name: Push changes
        run: |
          git push origin main
